version: "3"
services:
  app:
    container_name: app   
    restart: always
    build:
      context: ../.
      dockerfile: Docker/node/Dockerfile
    command: nodemon -L server.js
    ports:
      - "3000:3000"
    volumes:
      - ../app:/usr/src/app/
      - usr/src/app/node_modules/
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"